"""Deterministic schema -> TypeScript generator, with drift checking for CI.

Only the JSON Schema vocabulary emitted by app contracts is supported. New
schema features fail generation rather than silently weakening validation.
"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path
from pydantic import BaseModel, TypeAdapter

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from app.contracts import CLIENT_MODELS, JsonObject, JsonValue
from app.client_contracts import EXTRA_CLIENT_MODELS
from app.artist_settings import ArtistSettings
from app.tagging import TaggedDownloadOptions
from app.track_activity import TrackActivityResponse
from app.generation_contracts import GENERATION_CLIENT_MODELS
from app.yue_contracts import YUE_CLIENT_MODELS
from app.reference_contracts import REFERENCE_CLIENT_MODELS

ALL_MODELS: list[type[BaseModel]] = [*CLIENT_MODELS, *EXTRA_CLIENT_MODELS, ArtistSettings, TaggedDownloadOptions, TrackActivityResponse, *GENERATION_CLIENT_MODELS, *YUE_CLIENT_MODELS, *REFERENCE_CLIENT_MODELS]

DEST = Path(__file__).resolve().parents[2] / 'frontend/src/api/generated.ts'
SUPPORTED = {'$defs', '$ref', 'title', 'description', 'default', 'type', 'anyOf', 'enum', 'const', 'properties', 'required', 'additionalProperties', 'items', 'minimum', 'maximum', 'exclusiveMinimum', 'exclusiveMaximum', 'minLength', 'maxLength', 'minItems', 'maxItems', 'pattern'}


def object_of(value: JsonValue) -> JsonObject:
    if not isinstance(value, dict):
        raise ValueError('Expected schema object')
    return value


def list_of(value: JsonValue) -> list[JsonValue]:
    if not isinstance(value, list):
        raise ValueError('Expected schema array')
    return value


def string_of(value: JsonValue) -> str:
    if not isinstance(value, str):
        raise ValueError('Expected schema string')
    return value


def type_of(schema: JsonObject) -> str:
    unsupported = schema.keys() - SUPPORTED
    if unsupported:
        raise ValueError(f'Unsupported schema: {unsupported}')
    if '$ref' in schema:
        return string_of(schema['$ref']).rsplit('/', 1)[1]
    if 'anyOf' in schema:
        return '(' + ' | '.join(type_of(object_of(s)) for s in list_of(schema['anyOf'])) + ')'
    if 'enum' in schema:
        return ' | '.join(json.dumps(v) for v in list_of(schema['enum']))
    if 'const' in schema:
        return json.dumps(schema['const'])
    kind = schema.get('type')
    if kind == 'object':
        props = schema.get('properties')
        if props is not None:
            required = list_of(schema.get('required', []))
            return '{\n' + '\n'.join(f'  {json.dumps(k)}{"" if k in required else "?"}: {type_of(object_of(v))}' for k,v in object_of(props).items()) + '\n}'
        additional = schema.get('additionalProperties', True)
        return 'Record<string, ' + (type_of(additional) if isinstance(additional, dict) else 'unknown') + '>'
    if kind == 'array':
        return f'Array<{type_of(object_of(schema["items"]))}>'
    return {'string': 'string', 'integer': 'number', 'number': 'number', 'boolean': 'boolean', 'null': 'null'}[string_of(kind)]


def generate() -> str:
    definitions: dict[str, JsonObject] = {}
    for model in ALL_MODELS:
        schema = TypeAdapter(JsonObject).validate_python(model.model_json_schema(mode='serialization'))
        definitions.update({name: object_of(value) for name, value in object_of(schema.pop('$defs', {})).items()})
        definitions[model.__name__] = schema
    # Pydantic's JsonValue validates recursively but emits an unconstrained
    # JSON Schema. Encode that built-in JSON vocabulary for browser validation.
    if definitions.get('JsonValue') == {}:
        branches: list[JsonValue] = [
            {'type': kind} for kind in ('string', 'number', 'boolean', 'null')
        ]
        branches.extend([
            {'type': 'array', 'items': {'$ref': '#/$defs/JsonValue'}},
            {'type': 'object', 'additionalProperties': {'$ref': '#/$defs/JsonValue'}},
        ])
        definitions['JsonValue'] = {'anyOf': branches}
    output = '// Generated by backend/scripts/generate_contracts.py. Do not edit.\n'
    output += "import { decodeSchema } from './schemaValidation'\n\n"
    # Pydantic JsonValue is a recursive union and shares this name.
    for name,schema in sorted(definitions.items()):
        if name == 'JsonValue':
            output += 'export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue }\n\n'
        else:
            output += f'export type {name} = {type_of(schema)}\n\n'
    output += 'export type JsonObject = Record<string, JsonValue>\n\n'
    output += 'const schemas = ' + json.dumps(definitions, ensure_ascii=False, indent=2) + ' as const\n\n'
    if 'JsonValue' in definitions:
        output += 'export function isJsonValue(value: unknown): value is JsonValue {\n  return decodeSchema(schemas.JsonValue, value, schemas)\n}\n\n'
    for model in ALL_MODELS:
        name = model.__name__
        output += f'function is{name}(value: unknown): value is {name} {{\n  return decodeSchema(schemas.{name}, value, schemas)\n}}\n'
        output += f'export function parse{name}(value: unknown): {name} {{\n  if (!is{name}(value)) throw new TypeError("Invalid {name} response")\n  return value\n}}\n\n'
    return output.rstrip('\n') + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = generate()
    if args.check:
        if not DEST.exists() or DEST.read_text() != result:
            sys.exit('API contracts are stale; run python backend/scripts/generate_contracts.py')
    else:
        DEST.write_text(result)
